### ISSUE TITLE
Md5 Mismatch

### ISSUE THREAD

**Issue by jlaura** [conda-forge/vlfeat-feedstock#11]
Issue:
It looks like the md5 was not updated with a version updated. See: https://travis-ci.org/USGS-Astrogeology/autocnet/jobs/410066133#L820
<br/>

Conda Env:
<details>
```
This is a clean miniconda install on a travisCI provided image.  See: https://travis-ci.org/USGS-Astrogeology/autocnet/jobs/410066133#L820
```
</details>

**Comment by 183amir** [comment]
closing as too old
