### ISSUE TITLE
Not able to build vlfeat 

### ISSUE THREAD

**Issue by skbidiap** [conda-forge/vlfeat-feedstock#5]
Hi Patrick,
Compiling vlfeat crashes because it's not able to find dsift.h. 
Could you please add the header files to the package?
Thanks,
Sushil

**Comment by patricksnape** [comment]
The header files [are included](https://github.com/conda-forge/vlfeat-feedstock/blob/master/recipe/build.sh#L52). Can you give more information about your build setup?

**Comment by 183amir** [comment]
The compilation fails when it tries to compile `cyvlfeat`. Can we have that package on `conda-forge`?

**Comment by patricksnape** [comment]
I can make a package, sure.

**Comment by 183amir** [comment]
not related to vlfeat.
